### ISSUE TITLE
minSDK 19 seems to be possible

### ISSUE THREAD

**Issue by Hatzen** [TutorialsAndroid/FilePicker#11]
Also there are only 5% users using Android KitKat my app does support it actually and i doesnt want to upgrade for no reason.  
I just checkout your awesome project (thanks mate!) and lowered the minSDK version. It seems there is no issue by lowering it to minSDK 19 in the library gradle.build file. Testet with Firephone Android 4.4.4
Can you please downgrade the minSdk or is there any reason you dont want to?

**Comment by mrgames13** [comment]
Hey,
I saw your fork of the library. Please note, that you have to downgrade the minSdkVersion in the sample module as well. I've tested it on an emulator with Android 4.4 (API level 19) and it works correctly.
As far as I see, this library does not get maintained actively. You can just open a pull request. I'm sure the owner will merge it to master.

**Comment by Hatzen** [comment]
@mrgames13 thank you for your approval and motivation. I just opened a MR for this issue
