### ISSUE TITLE
I have star it, if down to minsdk 19 will be more great

### ISSUE THREAD

**Issue by zj2050** [TutorialsAndroid/FilePicker#12]
I have star it, if down to minsdk 19 will be more great

only 9 issue but 3 want down to minsdk 19 @TutorialsAndroid

**Comment by mrgames13** [comment]
@Hatzen Just opened a pull request for solving this. So this issue is a dupe.

**Comment by TutorialsAndroid** [comment]
i have merge the pull request to 19

> 
> 
> @Hatzen Just opened a pull request for solving this. So this issue is a dupe.

**Comment by zj2050** [comment]
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.TutorialsAndroid:FilePicker:v6.0.19] /Users/liugrant/.gradle/caches/transforms-2/files-2.1/78d0819ee15d244f2e3d7514c941583a/FilePicker-v6.0.19/AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,

**Comment by zj2050** [comment]
@Hatzen

**Comment by zj2050** [comment]
@TutorialsAndroid

**Comment by mrgames13** [comment]
You have to update the dependency to the library first. I see that you're using version 'v6.0.19'. This has to be 'v7.0.19'.

**Comment by TutorialsAndroid** [comment]
> 
> 
> You have to update the library first. I see that you're using version 'v6.0.19'. This has to be 'v7.0.19'.

i have updated the library to 7.0.19 download it.

> 
> 
> You have to update the library first. I see that you're using version 'v6.0.19'. This has to be 'v7.0.19'.
