### ISSUE TITLE
External Storage not showing

### ISSUE THREAD

**Issue by Mohammad-Adam** [TutorialsAndroid/FilePicker#17]
firstly thank you for your work;
secondly i can't see the external sd card;
thirdly can you show file size?

**Comment by slim-shah** [comment]
Hi, First of all, thank you so much for your work ! 

I am facing a small problem can you please help me with it. 
I am not able to view the files on my phone. I have made sure that i have used all the required permission in manifest file.

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Here the screeshot of error.
All the folders are empty and i am not able to view any other folders apart from these. And i know for sure that there are lot of folders under /mnt directory.

<img width="300" alt="Screen Shot 2021-02-12 at 5 14 09 PM" src="https://user-images.githubusercontent.com/16894312/107832806-08135880-6d57-11eb-9291-e146731a092a.png">

Thanks and advance !

**Comment by slim-shah** [comment]
Problem solved!

I was working on someone else's code and did not check the manifest file. The manifest file was missing the following code snippet.

```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting
       Android 10 or higher. -->
  <application 
       android:requestLegacyExternalStorage="true" ........ >
    ......
  </application>
</manifest>
```
I solved this error after reading the readMe file.

**Comment by TutorialsAndroid** [comment]
I have tried to solve this issue. But not exactly getting it. I'm still trying to solve this issue.

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version v9.0.1 and see the android 13 documentation in README.
