### ISSUE TITLE
Unable to see storage in Android 10

### ISSUE THREAD

**Issue by alifhasnain** [TutorialsAndroid/FilePicker#2]
I don't see any internal or external storage location even though I have `WRITE_EXTERNAL_STORAGE` permission when I open file picker dialog in Android Q.

**Comment by Xset-s** [comment]
I have the same issue. Any updates?

**Comment by alifhasnain** [comment]
No. I have not found any way to fix this and library creator is not replying.

**Comment by TutorialsAndroid** [comment]
> 
> 
> No. I have not found any way to fix this and library creator is not replying.

sorry for the late reply. we will be updating this library in 2 days to support android 10

**Comment by TutorialsAndroid** [comment]
> 
> 
> I have the same issue. Any updates?

sorry for late reply we will be updating this library in 2 days

**Comment by TutorialsAndroid** [comment]
> 
> 
> I don't see any internal or external storage location even though I have `WRITE_EXTERNAL_STORAGE` permission when I open file picker dialog in Android Q.

May be now it will work on android 10 i have updated this library

**Comment by TutorialsAndroid** [comment]
> 
> 
> I have the same issue. Any updates?


May be now it will work on android 10 i have updated this library

**Comment by TutorialsAndroid** [comment]
Download the latest verison of library v5.0.19

**Comment by alifhasnain** [comment]
The problem was `requestLegacyExternalStorage` was not set to `true` in the manifest file. Because of scoped external storage by default it is set to `false` in Android 10 or higher. Adding this line in the `AndroidManifest.xml` solved my problem.

```java
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting
       Android 10 or higher. -->
  <application 
       android:requestLegacyExternalStorage="true" ........ >
    ......
  </application>
</manifest>
```

**Comment by TutorialsAndroid** [comment]
> 
> 
> The problem was `requestLegacyExternalStorage` was not set to `true` in the manifest file. Because of scoped external storage by default it is set to `false` in Android 10 or higher. Adding this line in the `AndroidManifest.xml` solved my problem.
> 
> ```java
> <manifest ... >
>   
>   <application 
>        android:requestLegacyExternalStorage="true" ........ >
>     ......
>   </application>
> </manifest>
> ```

Thank you to solve this problem @alifhasnain

**Comment by giejay** [comment]
I am running the sample app on my Android 10 Emulator with an external sd card. The external sd card is not showing unfortunately. I only see 2 dirs under /mnt, asec and obb. Anyone knows how to fix this?

Edit: Ah.. Im running SDK 30, thats Android 10+. I guess that's not supported yet.

**Comment by klaszlo8207** [comment]
**I only see 2 dirs under /mnt, asec and obb. Anyone knows how to fix this?**

Any news on this? Android 11 not supported?

**Comment by klaszlo8207** [comment]
> I am running the sample app on my Android 10 Emulator with an external sd card. The external sd card is not showing unfortunately. I only see 2 dirs under /mnt, asec and obb. Anyone knows how to fix this?
> 
> Edit: Ah.. Im running SDK 30, thats Android 10+. I guess that's not supported yet.

How to fixed it???

**Comment by TutorialsAndroid** [comment]
Ok i will check this on this issue. I will update it soon in few days
