### ISSUE TITLE
Internal Storage not Showing

### ISSUE THREAD

**Issue by ManishAndroidIos** [TutorialsAndroid/FilePicker#20]
Hi SD card is showing but Internal Storage is not showing.

**Comment by slim-shah** [comment]
Hi I am facing the same problem. I am not able to view the files on my phone. I have made sure that i have used all the required permission in manifest file.

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

Here the screeshot of error.
All the folders are empty and i am not able to view any other folders apart from these. And i know for sure that there are lot of folders under /mnt directory.

<img width="300" alt="Screen Shot 2021-02-12 at 5 14 09 PM" src="https://user-images.githubusercontent.com/16894312/107832521-36446880-6d56-11eb-8fd1-b40721ebb3b4.png">

Thanks and advance !

**Comment by slim-shah** [comment]
Problem solved!

I was working on someone else's code and did not check the manifest file. The manifest file was missing the following code snippet.

```
<manifest ... >
  <!-- This attribute is "false" by default on apps targeting
       Android 10 or higher. -->
  <application 
       android:requestLegacyExternalStorage="true" ........ >
    ......
  </application>
</manifest>
```
I solved this error after reading the readMe file.

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version 9.1.4 and see the android 13 documentation in README.
