### ISSUE TITLE
Android 11 Does not showing  the internal storage folders and file

### ISSUE THREAD

**Issue by pankajjangid** [TutorialsAndroid/FilePicker#21]
In Android 11 there no files and folders in internal storage.
even I add the line in the android manifest file.

`android:requestLegacyExternalStorage="true"`

[https://i.imgur.com/1aw0txo.jpg](url)
[https://i.imgur.com/zpe7UWW.jpg](url)

**Comment by marcauberer** [comment]
@pankajjangid the reason for that is, that the library currently doesn't support scoped storage, which is mandatory for apps, targeting Android >= 11

**Comment by slim-shah** [comment]
I am facing the same problem. 

it did not worked for me but you can try this : 
https://stackoverflow.com/questions/63364476/requestlegacyexternalstorage-is-not-working-in-android-11-api-30

**Comment by AlbyST** [comment]
Hi all, I am facing the same problem too, I'm on Android 11.

I tried several options like:

* Targeting SDK 29 with ```android:requestLegacyExternalStorage="true"```
* Targeting SDK 30 with ```android:preserveLegacyExternalStorage="true"```
* Adding ```android.permission.READ_EXTERNAL_STORAGE``` and ```android.permission.WRITE_EXTERNAL_STORAGE``` to the manifest.xml

but nothing seems to work.

**Comment by klaszlo8207** [comment]
> Hi all, I am facing the same problem too, I'm on Android 11.
> 
> I tried several options like:
> 
>     * Targeting SDK 29 with `android:requestLegacyExternalStorage="true"`
> 
>     * Targeting SDK 30 with `android:preserveLegacyExternalStorage="true"`
> 
>     * Adding `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.WRITE_EXTERNAL_STORAGE` to the manifest.xml
> 
> 
> but nothing seems to work.

any news?

**Comment by TutorialsAndroid** [comment]
I have tried to solve this issue. But not exactly getting it. I'm still trying to solve this issue.

**Comment by mehedisoftware** [comment]
I am facing the same problem.

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version v9.0.1 and see the android 13 documentation in README.
