### ISSUE TITLE
How To set width of dialogue ???

### ISSUE THREAD

**Issue by rogerda8** [TutorialsAndroid/FilePicker#22]
Its too narrow that's why name of some files is not visible, is there any property to change width of dialogue box?

**Comment by SaJeTek-Developer** [comment]
What was the solution for this? I'm having the same issue. It's showing very narrow on screen.

**Comment by SaJeTek-Developer** [comment]
Solution for future reference is:

```
filePickerDialog.show();
filePickerDialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
```
