### ISSUE TITLE
Not able to find .csv files

### ISSUE THREAD

**Issue by Vinci-Hu** [TutorialsAndroid/FilePicker#25]
When I used this to browse the phone storage,files like jpg, mp3, png and stuff all can show. But some file types like .csv or .zip is unavailable. Like under the same directory there is a document and a photo, only the photo have its appearance in the picker dialog.
How to solve this please?

**Comment by TutorialsAndroid** [comment]
Your issue has been solved in latest version. Check out the new version and README for documentation.
