### ISSUE TITLE
android 11 only asec/obb directories

### ISSUE THREAD

**Issue by klaszlo8207** [TutorialsAndroid/FilePicker#26]
I can only see this two directiories on android 11+

**Comment by TutorialsAndroid** [comment]
I have tried to solve this issue. But not exactly getting it. I'm still trying to solve this issue.

**Comment by Earthlingz** [comment]
I was able to access the internal storage by using
        properties.root = new File("/storage/emulated/0");
        properties.error_dir = new File("/storage/emulated/0");
        properties.offset = new File("/storage/emulated/0");

but it looks like it only allow you to choose media files.

**Comment by molihuan** [comment]
> I can only see this two directiories on android 11+

you can look at my project: automatic application for storage permission, support Android 4.4 ~ 12, support Android/data directory access,but Android/obb not currently supported, support SD card.

https://github.com/molihuan/mlhfileselectorlib/blob/master/README_EN.md

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version v9.0.1 and see the android 13 documentation in README.
