### ISSUE TITLE
Android 11 Does not showing the internal storage

### ISSUE THREAD

**Issue by mehedisoftware** [TutorialsAndroid/FilePicker#27]
This file picker is the best but does not support Android version 11 any solution please

**Comment by molihuan** [comment]
> This file picker is the best but does not support Android version 11 any solution please

you can look at my project: automatic application for storage permission, support Android 4.4 ~ 12, support Android/data directory access, support SD card

https://github.com/molihuan/mlhfileselectorlib/blob/master/README_EN.md

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version v9.0.1 and see the android 13 documentation in README.
