### ISSUE TITLE
FilePickerDialog class not recognized in android studio

### ISSUE THREAD

**Issue by singhayush20** [TutorialsAndroid/FilePicker#28]
I am trying to implement this file picker dialog in a media app. The app build was successful after adding the dependency. But, the FilePickerDialog class is not recoginzed. Although, DialogProperties is recognized. Somebody, please help!

![image](https://user-images.githubusercontent.com/106401615/179345386-6ef39d40-372a-47f2-9c2c-914d2e787408.png)

**Comment by TutorialsAndroid** [comment]
Closing this issue for now because no one has encountered this type of problem
