### ISSUE TITLE
Bug: SDK 33

### ISSUE THREAD

**Issue by madiazg** [TutorialsAndroid/FilePicker#29]
Hi!
I want to report a bug when I update the app to SDK 33. Basically FilePicker doesn't run even though it doesn't give any error message.

compileSdkVersion 33
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 33
	.....

Regards...
Miguel Ángel

**Comment by ruslankd** [comment]
Please update

**Comment by madiazg** [comment]
Thanks for answering, I had updated to the new version and it seemed to work correctly.

If permissions are preserved from previous versions of the app (SDK 31) filepicker works correctly with SDK 33. That is, if I update the app from previous versions where read/write permissions have been given to the app, filepicker works correctly with SDK 33.

If I uninstall the app, removing the permissions and reinstall it, filepicker doesn't work (I think it's a read/write permissions problem).

Apparently, in SDK 33, the WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE permissions don't take them into account.

Regards...
Miguel Ángel

**Comment by ShivShrivas** [comment]
I'm not getting any type of solution for my App,
Kindly help me

and Please let me know, have you changed in Manifest file or anywhere else

Please...

**Comment by waqarul** [comment]
did anyone solved the issue?

**Comment by TutorialsAndroid** [comment]
I will update you soon on this issue. Working on a new filepicker version.

**Comment by TutorialsAndroid** [comment]
New update release to this library update to version v9.0.1 and see the android 13 documentation in README.
