### ISSUE TITLE
Select Current Directory

### ISSUE THREAD

**Issue by Kevanderson97** [TutorialsAndroid/FilePicker#5]
When doing a select for only a directory, the user should be able to click "select" with no sub-directories selected to choose the current directory. This seems like the most intuitive form of directory selection to me, plus it is fairly difficult to hit the check boxes next to directories, so this would allow one to misclick, go insde, and still select the intended directory. 

Additionally, would it be possible to add the ability to hit the check box for directories if you long-press the directory you want to select? I was very confused as to how to select the directory I wanted to choose when first using this because selecting the current directory wasn't an option and long-pressing it was my second instinct before clicking on the check box itself.

**Comment by TutorialsAndroid** [comment]
> When doing a select for only a directory, the user should be able to click "select" with no sub-directories selected to choose the current directory. This seems like the most intuitive form of directory selection to me, plus it is fairly difficult to hit the check boxes next to directories, so this would allow one to misclick, go insde, and still select the intended directory.
> 
> Additionally, would it be possible to add the ability to hit the check box for directories if you long-press the directory you want to select? I was very confused as to how to select the directory I wanted to choose when first using this because selecting the current directory wasn't an option and long-pressing it was my second instinct before clicking on the check box itself.

Sorry for late reply i will updating this library as i'm busy so couldn't get time for adding new features and all but i will try to update this library
