### ISSUE TITLE
FilePickerPreference not using AndroidX

### ISSUE THREAD

**Issue by svenoaks** [TutorialsAndroid/FilePicker#6]
The readme states that latest version uses AndroidX, but FilePickerPreference imports android.preference.Preference which is deprecated in favor of AndroidX preference compat libraries.

**Comment by TutorialsAndroid** [comment]
> The readme states that latest version uses AndroidX, but FilePickerPreference imports android.preference.Preference which is deprecated in favor of AndroidX preference compat libraries.

sorry for late. i will soon fixed that

**Comment by Hatzen** [comment]
FYI 
Also it would be more pretty to use androidx it is still compatible with my androidx based project.
